/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class _Included_jp_sacredsanctuary_helloworld_nativeaccess_NativeAccess */

#ifndef _Included_jp_sacredsanctuary_helloworld_nativeaccess_NativeAccess
#define _Included_jp_sacredsanctuary_helloworld_nativeaccess_NativeAccess

#include <vector>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL
Java_jp_sacredsanctuary_helloworld_nativeaccess_NativeAccess_onServiceConnectedJNI(
        JNIEnv *env, jobject thiz);

JNIEXPORT void JNICALL
Java_jp_sacredsanctuary_helloworld_nativeaccess_NativeAccess_onServiceDisconnected(
        JNIEnv *env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
